"""empty message

Revision ID: 25f1b5cbbc8e
Revises: 4ea239fe8a5c
Create Date: 2020-09-22 17:46:02.410767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f1b5cbbc8e'
down_revision = '4ea239fe8a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=255), nullable=True),
    sa.Column('referrer', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('permission', sa.Column('level', sa.Integer(), nullable=True, comment='权限等级'))
    op.drop_constraint('role_permission_ibfk_1', 'role_permission', type_='foreignkey')
    op.drop_constraint('role_permission_ibfk_2', 'role_permission', type_='foreignkey')
    op.create_foreign_key(None, 'role_permission', 'permission', ['pid'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permission', 'role', ['rid'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('lock', sa.BOOLEAN(), server_default=sa.text('False'), nullable=True, comment='用户锁定'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lock')
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.create_foreign_key('role_permission_ibfk_2', 'role_permission', 'role', ['rid'], ['id'])
    op.create_foreign_key('role_permission_ibfk_1', 'role_permission', 'permission', ['pid'], ['id'])
    op.drop_column('permission', 'level')
    op.drop_table('site')
    # ### end Alembic commands ###
