"""empty message

Revision ID: a77146860959
Revises: a7855ad596d0
Create Date: 2020-09-03 20:29:17.088185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77146860959'
down_revision = 'a7855ad596d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('icon', sa.String(length=32), server_default='el-icon-s-home', nullable=True, comment='菜单图标'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission', 'icon')
    # ### end Alembic commands ###
