"""empty message

Revision ID: e6f9bc78a4b6
Revises: 
Create Date: 2020-09-01 18:02:49.311269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f9bc78a4b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_body',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('is_delete', sa.BOOLEAN(), server_default=sa.text('False'), nullable=True, comment='是否删除'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('content_html', sa.Text(), nullable=True, comment='文章的html'),
    sa.Column('content', sa.Text(), nullable=True, comment='文章内容'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('is_delete', sa.BOOLEAN(), server_default=sa.text('False'), nullable=True, comment='是否删除'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('category_name', sa.String(length=32), nullable=True, comment='分类名称'),
    sa.Column('alias', sa.String(length=32), nullable=True, comment='别名'),
    sa.Column('desc', sa.String(length=255), nullable=True, comment='分类描述'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('friend',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('is_delete', sa.BOOLEAN(), server_default=sa.text('False'), nullable=True, comment='是否删除'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('friend_name', sa.String(length=64), nullable=True, comment='好友名称'),
    sa.Column('desc', sa.String(length=255), nullable=True, comment='好友描述'),
    sa.Column('friend_link', sa.String(length=64), nullable=True, comment='友链'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('is_delete', sa.BOOLEAN(), server_default=sa.text('False'), nullable=True, comment='是否删除'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('auth_name', sa.String(length=32), nullable=True, comment='权限名称'),
    sa.Column('desc', sa.String(length=256), nullable=True, comment='权限描述'),
    sa.Column('path', sa.String(length=32), nullable=True, comment='路由'),
    sa.Column('order', sa.Integer(), nullable=True, comment='展示顺序'),
    sa.Column('method', sa.String(length=6), server_default='get', nullable=True, comment='请求方法'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级权限id'),
    sa.ForeignKeyConstraint(['parent_id'], ['permission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('is_delete', sa.BOOLEAN(), server_default=sa.text('False'), nullable=True, comment='是否删除'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('module', sa.String(length=16), nullable=True, comment='操作模块'),
    sa.Column('type', sa.Integer(), nullable=False, comment='操作类型'),
    sa.Column('content', sa.String(length=256), server_default='-', nullable=True, comment='操作详情'),
    sa.Column('create_by', sa.Integer(), nullable=True, comment='操作人id'),
    sa.Column('create__by_name', sa.String(length=32), nullable=True, comment='操作人名称'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('is_delete', sa.BOOLEAN(), server_default=sa.text('False'), nullable=True, comment='是否删除'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('name', sa.String(length=32), nullable=True, comment='角色名称'),
    sa.Column('desc', sa.String(length=256), nullable=True, comment='角色描述'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('is_delete', sa.BOOLEAN(), server_default=sa.text('False'), nullable=True, comment='是否删除'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('name', sa.String(length=24), nullable=True, comment='标签名称'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('is_delete', sa.BOOLEAN(), server_default=sa.text('False'), nullable=True, comment='是否删除'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('email', sa.String(length=120), nullable=True, comment='邮箱'),
    sa.Column('nickname', sa.String(length=32), nullable=True, comment='名称'),
    sa.Column('pwd', sa.String(length=128), nullable=True, comment='密码'),
    sa.Column('signature', sa.String(length=256), nullable=True, comment='个性签名'),
    sa.Column('avatar', sa.String(length=128), nullable=True, comment='头像'),
    sa.Column('last_login', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='最近登录时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('is_delete', sa.BOOLEAN(), server_default=sa.text('False'), nullable=True, comment='是否删除'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('title', sa.String(length=64), nullable=True, comment='文章标题'),
    sa.Column('desc', sa.String(length=500), nullable=True, comment='文章简介'),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='作者id'),
    sa.Column('body_id', sa.Integer(), nullable=True, comment='文章结构体id'),
    sa.Column('view_counts', sa.Integer(), server_default='0', nullable=True, comment='文章阅读数'),
    sa.Column('weight', sa.Integer(), nullable=True, comment='置顶功能'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类'),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['body_id'], ['article_body.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('body_id')
    )
    op.create_table('role_permission',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['rid'], ['role.id'], ),
    sa.PrimaryKeyConstraint('rid', 'pid')
    )
    op.create_table('user_role',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rid'], ['role.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('uid', 'rid')
    )
    op.create_table('article_tag',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aid'], ['article.id'], ),
    sa.ForeignKeyConstraint(['tid'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tid', 'aid')
    )
    op.create_table('comment',
    sa.Column('is_delete', sa.BOOLEAN(), server_default=sa.text('False'), nullable=True, comment='是否删除'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('author', sa.String(length=30), nullable=True, comment='评论者名称'),
    sa.Column('email', sa.String(length=64), nullable=True, comment='评论者邮箱'),
    sa.Column('site', sa.String(length=64), nullable=True, comment='评论者网址'),
    sa.Column('body', sa.Text(), nullable=True, comment='评论内容'),
    sa.Column('from_admin', sa.Boolean(), nullable=True, comment='来自作者'),
    sa.Column('commented_post_id', sa.Integer(), nullable=True, comment='评论文章id'),
    sa.Column('replied_id', sa.Integer(), nullable=True, comment='回复id'),
    sa.ForeignKeyConstraint(['commented_post_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['replied_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('article_tag')
    op.drop_table('user_role')
    op.drop_table('role_permission')
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('role')
    op.drop_table('record')
    op.drop_table('permission')
    op.drop_table('friend')
    op.drop_table('category')
    op.drop_table('article_body')
    # ### end Alembic commands ###
