"""empty message

Revision ID: ec13e656b5cc
Revises: a77146860959
Create Date: 2020-09-07 21:22:01.968740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec13e656b5cc'
down_revision = 'a77146860959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_addr', sa.String(length=64), nullable=True, comment='登录地址'))
    op.add_column('user', sa.Column('login_ip', sa.String(length=16), nullable=True, comment='登录ip'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_ip')
    op.drop_column('user', 'login_addr')
    # ### end Alembic commands ###
